name: reverse
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: echo "Hello there!"
      - run: npm install
      - run: npm install -g jest --save--dev
      - run: npm run test
